# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 21:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='email',
            new_name='confirm_pw',
        ),
    ]
