# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 21:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_auto_20161118_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='planned_by',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
