# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 21:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_auto_20161118_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='travel.Users'),
        ),
    ]
