# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_remove_users_confirm_pw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
