# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 02:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0009_auto_20161121_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='join',
            name='location_id',
        ),
        migrations.RemoveField(
            model_name='join',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='location',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Join',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
